### ISSUE TITLE
Support "watch" command

### ISSUE THREAD

**Issue by c9s** [c9s/AssetKit#14]
Example asset config:

```yaml
collections:
  - javascript:
    - foo.js
    compiler: coffee
    source:
    - foo.coffee
  - stylesheet:
    - theme.css
    compiler: sass
    source:
    - foo.sass
    - sass:css
```

Command:

```
assetkit watch jquery-ui project-a
```

**Comment by c9s** [comment]
Example of the "compile" option:

```yaml
collections:
  - javascript:
    - foo.js
    compile: coffee -wc --join foo.coffee foo.js
```
